const records = [
  {
    author: "Suzanne Collins",
    title: "The Hunger Games",
    genre: "Young Adult",
    date: "14-09-2008",
  },
  {
    author: "J.K. Rowling",
    title: "Harry Potter and the Order of the Phoenix",
    genre: "Fantasy",
    date: "28-09-2004",
  },
  {
    author: "Harper Lee",
    title: "To Kill a Mockingbird",
    genre: "Classics",
    date: "23-05-2006",
  },
  {
    author: "Jane Austen",
    title: "Pride and Prejudice",
    genre: "Classics",
    date: "10-10-2000",
  },
  {
    author: "Stephenie Meyer",
    title: "Twilight",
    genre: "Young Adult",
    date: "06-09-2006",
  },
  {
    author: "Markus Zusak (Goodreads Author)",
    title: "The Book Thief",
    genre: "Historical Fiction",
    date: "14-03-2006",
  },
  {
    author: "George Orwell",
    title: "Animal Farm",
    genre: "Classics",
    date: "28-04-1996",
  },
  {
    author: "C.S. Lewis",
    title: "The Chronicles of Narnia",
    genre: "Fantasy",
    date: "16-09-2002",
  },
  {
    author: "J.R.R. Tolkien",
    title:
      "J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings",
    genre: "Fantasy",
    date: "25-09-2012",
  },
  {
    author: "Margaret Mitchell",
    title: "Gone with the Wind",
    genre: "Classics",
    date: "01-04-1999",
  },
  {
    author: "John Green (Goodreads Author)",
    title: "The Fault in Our Stars",
    genre: "Young Adult",
    date: "10-01-2012",
  },
  {
    author: "Douglas Adams",
    title: "The Hitchhiker's Guide to the Galaxy",
    genre: "Science Fiction",
    date: "23-06-2007",
  },
  {
    author: "Shel Silverstein",
    title: "The Giving Tree",
    genre: "Childrens",
    date: "07-10-2064",
  },
  {
    author: "Emily Bront\u00eb",
    title: "Wuthering Heights",
    genre: "Classics",
    date: "28-10-2002",
  },
  {
    author: "Dan Brown (Goodreads Author)",
    title: "The Da Vinci Code",
    genre: "Fiction",
    date: "28-03-2006",
  },
  {
    author: "Arthur Golden",
    title: "Memoirs of a Geisha",
    genre: "Fiction",
    date: "22-11-2005",
  },
  {
    author: "Oscar Wilde",
    title: "The Picture of Dorian Gray",
    genre: "Classics",
    date: "01-06-2004",
  },
  {
    author: "Lewis Carroll",
    title: "Alice's Adventures in Wonderland & Through the Looking-Glass",
    genre: "Classics",
    date: "01-12-2000",
  },
  {
    author: "Charlotte Bront\u00eb",
    title: "Jane Eyre",
    genre: "Classics",
    date: "04-02-2003",
  },
  {
    author: "Victor Hugo",
    title: "Les Mis\u00e9rables",
    genre: "Classics",
    date: "03-03-1987",
  },
  {
    author: "Ray Bradbury",
    title: "Fahrenheit 451",
    genre: "Classics",
    date: "29-11-2011",
  },
  {
    author: "Veronica Roth (Goodreads Author)",
    title: "Divergent",
    genre: "Young Adult",
    date: "28-02-2012",
  },
  {
    author: "William Golding",
    title: "Lord of the Flies",
    genre: "Classics",
    date: "01-10-1999",
  },
  {
    author: "William Shakespeare",
    title: "Romeo and Juliet",
    genre: "Classics",
    date: "01-01-2004",
  },
  {
    author: "Paulo Coelho (Goodreads Author)",
    title: "The Alchemist",
    genre: "Fiction",
    date: "15-04-2014",
  },
  {
    author: "Fyodor Dostoyevsky",
    title: "Crime and Punishment",
    genre: "Classics",
    date: "31-12-2002",
  },
  {
    author: "Stephen Chbosky",
    title: "The Perks of Being a Wallflower",
    genre: "Young Adult",
    date: "28-02-1999",
  },
  {
    author: "F. Scott Fitzgerald",
    title: "The Great Gatsby",
    genre: "Classics",
    date: "28-09-2004",
  },
  {
    author: "Cassandra Clare (Goodreads Author)",
    title: "City of Bones",
    genre: "Fantasy",
    date: "27-03-2007",
  },
  {
    author: "Orson Scott Card",
    title: "Ender's Game",
    genre: "Science Fiction",
    date: "30-09-2004",
  },
  {
    author: "Kathryn Stockett (Goodreads Author)",
    title: "The Help",
    genre: "Fiction",
    date: "10-02-2009",
  },
  {
    author: "L.M. Montgomery",
    title: "Anne of Green Gables",
    genre: "Classics",
    date: "06-05-2003",
  },
  {
    author: "J.K. Rowling",
    title: "Harry Potter and the Sorcerer's Stone",
    genre: "Fantasy",
    date: "01-11-2003",
  },
  {
    author: "Antoine de Saint-Exup\u00e9ry",
    title: "The Little Prince",
    genre: "Classics",
    date: "29-06-2000",
  },
  {
    author: "E.B. White",
    title: "Charlotte's Web",
    genre: "Classics",
    date: "01-10-2001",
  },
  {
    author: "John Steinbeck",
    title: "Of Mice and Men",
    genre: "Classics",
    date: "08-01-2002",
  },
  {
    author: "Audrey Niffenegger (Goodreads Author)",
    title: "The Time Traveler's Wife",
    genre: "Fiction",
    date: "23-09-2013",
  },
  {
    author: "Bram Stoker",
    title: "Dracula",
    genre: "Classics",
    date: "12-05-1986",
  },
  {
    author: "Aldous Huxley",
    title: "Brave New World",
    genre: "Classics",
    date: "01-09-1998",
  },
  {
    author: "Gabriel Garc\u00eda M\u00e1rquez",
    title: "One Hundred Years of Solitude",
    genre: "Fiction",
    date: "24-06-2003",
  },
  {
    author: "J.D. Salinger",
    title: "The Catcher in the Rye",
    genre: "Classics",
    date: "30-01-2001",
  },
  {
    author: "William Goldman",
    title: "The Princess Bride",
    genre: "Fantasy",
    date: "15-07-2003",
  },
  {
    author: "Rick Riordan (Goodreads Author)",
    title: "The Lightning Thief",
    genre: "Fantasy",
    date: "01-03-2006",
  },
  {
    author: "Frances Hodgson Burnett",
    title: "The Secret Garden",
    genre: "Classics",
    date: "01-09-1998",
  },
  {
    author: "Khaled Hosseini (Goodreads Author)",
    title: "A Thousand Splendid Suns",
    genre: "Fiction",
    date: "01-06-2007",
  },
  {
    author: "Madeleine L'Engle",
    title: "A Wrinkle in Time",
    genre: "Fantasy",
    date: "07-11-2017",
  },
  {
    author: "George R.R. Martin",
    title: "A Game of Thrones",
    genre: "Fantasy",
    date: "28-08-2005",
  },
  {
    author: "Mark Twain",
    title: "The Adventures of Huckleberry Finn",
    genre: "Classics",
    date: "31-12-2002",
  },
  {
    author: "Alice Sebold",
    title: "The Lovely Bones",
    genre: "Fiction",
    date: "01-09-2006",
  },
  {
    author: "S.E. Hinton (Goodreads Author)",
    title: "The Outsiders",
    genre: "Classics",
    date: "01-09-1997",
  },
  {
    author: "Maurice Sendak",
    title: "Where the Wild Things Are",
    genre: "Childrens",
    date: "28-10-2000",
  },
  {
    author: "Dr. Seuss",
    title: "Green Eggs and Ham",
    genre: "Childrens",
    date: "28-10-1988",
  },
  {
    author: "Homer",
    title: "The Odyssey",
    genre: "Classics",
    date: "30-11-2006",
  },
  {
    author: "Yann Martel",
    title: "Life of Pi",
    genre: "Fiction",
    date: "29-08-2006",
  },
  {
    author: "Charles Dickens",
    title: "A Tale of Two Cities",
    genre: "Classics",
    date: "28-10-2003",
  },
  {
    author: "Sara Gruen (Goodreads Author)",
    title: "Water for Elephants",
    genre: "Fiction",
    date: "01-05-2007",
  },
  {
    author: "Vladimir Nabokov",
    title: "Lolita",
    genre: "Classics",
    date: "28-10-1995",
  },
  {
    author: "Kurt Vonnegut Jr.",
    title: "Slaughterhouse-Five",
    genre: "Classics",
    date: "12-01-1999",
  },
  {
    author: "Mary Wollstonecraft Shelley",
    title: "Frankenstein: The 1818 Text",
    genre: "Classics",
    date: "08-03-2018",
  },
  {
    author: "Khaled Hosseini (Goodreads Author)",
    title: "The Kite Runner",
    genre: "Fiction",
    date: "28-05-2004",
  },
  {
    author: "Margaret Atwood (Goodreads Author)",
    title: "The Handmaid's Tale",
    genre: "Fiction",
    date: "28-04-1998",
  },
  {
    author: "Lois Lowry (Goodreads Author)",
    title: "The Giver",
    genre: "Young Adult",
    date: "24-01-2006",
  },
  {
    author: "Joseph Heller",
    title: "Catch-22",
    genre: "Classics",
    date: "04-09-2004",
  },
  {
    author: "Frank Herbert",
    title: "Dune",
    genre: "Science Fiction",
    date: "01-10-2019",
  },
  {
    author: "Ken Follett (Goodreads Author)",
    title: "The Pillars of the Earth",
    genre: "Historical Fiction",
    date: "04-02-2002",
  },
  {
    author: "Stephen King (Goodreads Author)",
    title: "The Stand",
    genre: "Horror",
    date: "01-05-1990",
  },
  {
    author: "Arthur Conan Doyle",
    title: "The Adventures of Sherlock Holmes",
    genre: "Classics",
    date: "22-10-1998",
  },
  {
    author: "Richard Adams",
    title: "Watership Down",
    genre: "Classics",
    date: "28-06-1975",
  },
  {
    author: "Charles Dickens",
    title: "Great Expectations",
    genre: "Classics",
    date: "28-10-1998",
  },
  {
    author: "Louisa May Alcott",
    title: "Little Women",
    genre: "Classics",
    date: "06-04-2004",
  },
  {
    author: "Sylvia Plath",
    title: "The Bell Jar",
    genre: "Classics",
    date: "28-10-2006",
  },
  {
    author: "J.K. Rowling",
    title: "Harry Potter and the Deathly Hallows",
    genre: "Fantasy",
    date: "21-07-2007",
  },
  {
    author: "Ken Kesey",
    title: "One Flew Over the Cuckoo's Nest",
    genre: "Classics",
    date: "01-02-2063",
  },
  {
    author: "Leo Tolstoy",
    title: "Anna Karenina",
    genre: "Classics",
    date: "16-10-2012",
  },
  {
    author: "Diana Gabaldon (Goodreads Author)",
    title: "Outlander",
    genre: "Historical Fiction",
    date: "26-07-2005",
  },
  {
    author: "Jodi Picoult (Goodreads Author)",
    title: "My Sister's Keeper",
    genre: "Fiction",
    date: "01-02-2005",
  },
  {
    author: "Roald Dahl",
    title: "Matilda",
    genre: "Childrens",
    date: "01-06-1998",
  },
  {
    author: "J.R.R. Tolkien",
    title: "The Fellowship of the Ring",
    genre: "Classics",
    date: "28-03-1973",
  },
  {
    author: "Stieg Larsson",
    title: "The Girl with the Dragon Tattoo",
    genre: "Fiction",
    date: "16-09-2008",
  },
  {
    author: "Daphne du Maurier",
    title: "Rebecca",
    genre: "Classics",
    date: "17-12-2013",
  },
  {
    author: "George Orwell",
    title: "1984",
    genre: "Classics",
    date: "03-09-2013",
  },
  {
    author: "Alice Walker",
    title: "The Color Purple",
    genre: "Classics",
    date: "10-12-2019",
  },
  {
    author: "Betty Smith",
    title: "A Tree Grows in Brooklyn",
    genre: "Classics",
    date: "30-05-2006",
  },
  {
    author: "Anthony Burgess",
    title: "A Clockwork Orange",
    genre: "Classics",
    date: "21-05-2019",
  },
  {
    author: "Cormac McCarthy",
    title: "The Road",
    genre: "Fiction",
    date: "02-10-2006",
  },
  {
    author: "Fyodor Dostoyevsky",
    title: "The Brothers Karamazov",
    genre: "Classics",
    date: "14-06-2002",
  },
  {
    author: "Frank McCourt",
    title: "Angela's Ashes",
    genre: "Nonfiction",
    date: "03-10-2005",
  },
  {
    author: "Richelle Mead (Goodreads Author)",
    title: "Vampire Academy",
    genre: "Young Adult",
    date: "16-08-2007",
  },
  {
    author: "Hermann Hesse",
    title: "Siddhartha",
    genre: "Classics",
    date: "01-12-1981",
  },
  {
    author: "Barbara Kingsolver",
    title: "The Poisonwood Bible",
    genre: "Fiction",
    date: "05-07-2005",
  },
  {
    author: "Philip Pullman",
    title: "The Golden Compass",
    genre: "Fantasy",
    date: "16-04-1996",
  },
  {
    author: "Miguel de Cervantes Saavedra",
    title: "Don Quixote",
    genre: "Classics",
    date: "25-02-2003",
  },
  {
    author: "Ayn Rand",
    title: "Atlas Shrugged",
    genre: "Classics",
    date: "01-08-1999",
  },
  {
    author: "J.K. Rowling",
    title: "Harry Potter and the Prisoner of Azkaban",
    genre: "Fantasy",
    date: "01-05-2004",
  },
  {
    author: "Ernest Hemingway",
    title: "The Old Man and the Sea",
    genre: "Classics",
    date: "28-10-1996",
  },
  {
    author: "Nicholas Sparks (Goodreads Author)",
    title: "The Notebook",
    genre: "Romance",
    date: "05-01-2000",
  },
  {
    author: "A.A. Milne",
    title: "Winnie-the-Pooh",
    genre: "Classics",
    date: "01-10-2001",
  },
  {
    author: "Edgar Allan Poe",
    title: "The Complete Stories and Poems",
    genre: "Classics",
    date: "15-08-1984",
  },
  {
    author: "Anne Rice",
    title: "Interview with the Vampire",
    genre: "Horror",
    date: "31-08-2004",
  },
  {
    author: "John Irving (Goodreads Author)",
    title: "A Prayer for Owen Meany",
    genre: "Fiction",
    date: "28-10-1990",
  },
  {
    author: "Herman Melville",
    title: "Moby-Dick or, the Whale",
    genre: "Classics",
    date: "21-02-2003",
  },
  {
    author: "Anita Diamant (Goodreads Author)",
    title: "The Red Tent",
    genre: "Historical Fiction",
    date: "28-10-1997",
  },
  {
    author: "Sue Monk Kidd (Goodreads Author)",
    title: "The Secret Life of Bees",
    genre: "Fiction",
    date: "28-01-2003",
  },
  {
    author: "J.K. Rowling",
    title: "Harry Potter and the Goblet of Fire",
    genre: "Fantasy",
    date: "28-09-2002",
  },
  {
    author: "Cassandra Clare (Goodreads Author)",
    title: "Clockwork Angel",
    genre: "Fantasy",
    date: "31-08-2010",
  },
  {
    author: "J.K. Rowling",
    title: "Harry Potter and the Half-Blood Prince",
    genre: "Fantasy",
    date: "16-09-2006",
  },
  {
    author: "Agatha Christie",
    title: "And Then There Were None",
    genre: "Mystery",
    date: "03-05-2004",
  },
  {
    author: "Jeffrey Eugenides",
    title: "Middlesex",
    genre: "Fiction",
    date: "16-09-2003",
  },
  {
    author: "Albert Camus",
    title: "The Stranger",
    genre: "Classics",
    date: "28-03-1989",
  },
  {
    author: "Mikhail Bulgakov",
    title: "The Master and Margarita",
    genre: "Classics",
    date: "28-03-1996",
  },
  {
    author: "Patrick Rothfuss (Goodreads Author)",
    title: "The Name of the Wind",
    genre: "Fantasy",
    date: "28-04-2007",
  },
  {
    author: "Stephen King (Goodreads Author)",
    title: "The Shining",
    genre: "Horror",
    date: "01-07-1980",
  },
  {
    author: "Mark Twain",
    title: "The Adventures of Tom Sawyer",
    genre: "Classics",
    date: "28-02-2006",
  },
  {
    author: "Christopher Paolini (Goodreads Author)",
    title: "Eragon",
    genre: "Fantasy",
    date: "28-04-2005",
  },
  {
    author: "Roald Dahl",
    title: "Charlie and the Chocolate Factory",
    genre: "Childrens",
    date: "02-06-2005",
  },
  {
    author: "Jack Kerouac",
    title: "On the Road",
    genre: "Classics",
    date: "01-01-1976",
  },
  {
    author: "Franz Kafka",
    title: "The Metamorphosis",
    genre: "Classics",
    date: "01-03-1972",
  },
  {
    author: "John Green (Goodreads Author)",
    title: "Looking for Alaska",
    genre: "Young Adult",
    date: "28-12-2006",
  },
  {
    author: "Carlos Ruiz Zaf\u00f3n",
    title: "The Shadow of the Wind",
    genre: "Fiction",
    date: "28-10-2005",
  },
  {
    author: "Mark Haddon",
    title: "The Curious Incident of the Dog in the Night-Time",
    genre: "Fiction",
    date: "18-05-2004",
  },
  {
    author: "Eric Carle",
    title: "The Very Hungry Caterpillar",
    genre: "Picture Books",
    date: "28-10-1994",
  },
  {
    author: "Mitch Albom (Goodreads Author)",
    title: "Tuesdays with Morrie",
    genre: "Nonfiction",
    date: "28-10-2000",
  },
  {
    author: "Milan Kundera",
    title: "The Unbearable Lightness of Being",
    genre: "Fiction",
    date: "27-10-2009",
  },
  {
    author: "Umberto Eco",
    title: "The Name of the Rose",
    genre: "Fiction",
    date: "28-09-1994",
  },
  {
    author: "Wilson Rawls",
    title: "Where the Red Fern Grows",
    genre: "Classics",
    date: "09-05-2000",
  },
  {
    author: "J.K. Rowling",
    title: "Harry Potter and the Chamber of Secrets",
    genre: "Fantasy",
    date: "02-06-1999",
  },
  {
    author: "Mario Puzo",
    title: "The Godfather",
    genre: "Fiction",
    date: "01-03-2002",
  },
  {
    author: "Nathaniel Hawthorne",
    title: "The Scarlet Letter",
    genre: "Classics",
    date: "27-02-2003",
  },
  {
    author: "Truman Capote",
    title: "In Cold Blood",
    genre: "Nonfiction",
    date: "28-10-1994",
  },
  {
    author: "Chuck Palahniuk (Goodreads Author)",
    title: "Fight Club",
    genre: "Fiction",
    date: "01-05-2018",
  },
  {
    author: "Mitch Albom (Goodreads Author)",
    title: "The Five People You Meet in Heaven",
    genre: "Fiction",
    date: "23-09-2003",
  },
  {
    author: "Becca Fitzpatrick (Goodreads Author)",
    title: "Hush, Hush",
    genre: "Young Adult",
    date: "13-10-2009",
  },
  {
    author: "Dr. Seuss",
    title: "The Cat in the Hat",
    genre: "Childrens",
    date: "28-10-1985",
  },
  {
    author: "Neil Gaiman (Goodreads Author)",
    title: "American Gods",
    genre: "Fantasy",
    date: "21-06-2011",
  },
  {
    author: "Alexandre Dumas",
    title: "The Count of Monte Cristo",
    genre: "Classics",
    date: "27-05-2003",
  },
  {
    author: "Larry McMurtry",
    title: "Lonesome Dove",
    genre: "Fiction",
    date: "01-10-1999",
  },
  {
    author: "Patrick S\u00fcskind",
    title: "Perfume: The Story of a Murderer",
    genre: "Fiction",
    date: "28-10-1987",
  },
  {
    author: "Louis Sachar (Goodreads Author)",
    title: "Holes",
    genre: "Young Adult",
    date: "02-09-2000",
  },
  {
    author: "C.S. Lewis",
    title: "The Lion, the Witch and the Wardrobe",
    genre: "Fantasy",
    date: "28-10-2005",
  },
  {
    author: "Alan Moore (Goodreads Author)",
    title: "Watchmen",
    genre: "Graphic Novels",
    date: "28-10-2005",
  },
  {
    author: "Stephen King (Goodreads Author)",
    title: "It",
    genre: "Horror",
    date: "01-10-1987",
  },
  {
    author: "Rick Riordan (Goodreads Author)",
    title: "The Last Olympian",
    genre: "Fantasy",
    date: "05-05-2009",
  },
  {
    author: "Laura Ingalls Wilder",
    title: "The Little House Collection",
    genre: "Classics",
    date: "07-10-2003",
  },
  {
    author: "Dante Alighieri",
    title: "The Divine Comedy",
    genre: "Classics",
    date: "01-08-1995",
  },
  {
    author: "J.M. Barrie",
    title: "Peter Pan",
    genre: "Classics",
    date: "01-10-2003",
  },
  {
    author: "Erich Maria Remarque",
    title: "All Quiet on the Western Front",
    genre: "Classics",
    date: "12-03-1987",
  },
  {
    author: "J.R.R. Tolkien",
    title: "The Hobbit, or There and Back Again",
    genre: "Fantasy",
    date: "15-08-2002",
  },
  {
    author: "Reduced Shakespeare Company",
    title: "The Compleat Works of Wllm Shkspr (abridged)",
    genre: "Plays",
    date: "01-02-1994",
  },
  {
    author: "Gabriel Garc\u00eda M\u00e1rquez",
    title: "Love in the Time of Cholera",
    genre: "Fiction",
    date: "05-10-2003",
  },
  {
    author: "Richelle Mead (Goodreads Author)",
    title: "Shadow Kiss",
    genre: "Young Adult",
    date: "13-11-2008",
  },
  {
    author: "Veronica Roth (Goodreads Author)",
    title: "Insurgent",
    genre: "Young Adult",
    date: "01-05-2012",
  },
  {
    author: "Colleen McCullough",
    title: "The Thorn Birds",
    genre: "Fiction",
    date: "28-10-2002",
  },
  {
    author: "Nicholas Sparks (Goodreads Author)",
    title: "A Walk to Remember",
    genre: "Romance",
    date: "24-05-2000",
  },
  {
    author: "Dr. Seuss",
    title: "How the Grinch Stole Christmas!",
    genre: "Childrens",
    date: "04-10-2004",
  },
  {
    author: "Douglas Adams",
    title: "The Ultimate Hitchhiker's Guide to the Galaxy",
    genre: "Science Fiction",
    date: "28-04-2002",
  },
  {
    author: "Ian McEwan",
    title: "Atonement",
    genre: "Fiction",
    date: "28-03-2003",
  },
  {
    author: "Oscar Wilde",
    title: "The Importance of Being Earnest",
    genre: "Classics",
    date: "28-10-2005",
  },
  {
    author: "Elizabeth Gilbert (Goodreads Author)",
    title: "Eat, Pray, Love",
    genre: "Nonfiction",
    date: "01-02-2007",
  },
  {
    author: "Zora Neale Hurston",
    title: "Their Eyes Were Watching God",
    genre: "Classics",
    date: "30-05-2006",
  },
  {
    author: "Alexandre Dumas",
    title: "The Three Musketeers",
    genre: "Classics",
    date: "13-02-2001",
  },
  {
    author: "L. Frank Baum",
    title: "The Wonderful Wizard of Oz",
    genre: "Classics",
    date: "28-10-1995",
  },
  {
    author: "Richelle Mead (Goodreads Author)",
    title: "Frostbite",
    genre: "Young Adult",
    date: "10-04-2008",
  },
  {
    author: "Margaret Wise Brown",
    title: "Goodnight Moon",
    genre: "Childrens",
    date: "23-01-2007",
  },
  {
    author: "Dr. Seuss",
    title: "The Lorax",
    genre: "Childrens",
    date: "24-02-1998",
  },
  {
    author: "Terry Pratchett",
    title:
      "Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch",
    genre: "Fantasy",
    date: "28-11-2006",
  },
  {
    author: "Richelle Mead (Goodreads Author)",
    title: "Blood Promise",
    genre: "Young Adult",
    date: "25-08-2009",
  },
  {
    author: "Thomas Hardy",
    title: "Tess of the D'Urbervilles",
    genre: "Classics",
    date: "30-01-2003",
  },
  {
    author: "Pearl S. Buck",
    title: "The Good Earth",
    genre: "Classics",
    date: "04-03-2009",
  },
  {
    author: "Joseph Conrad",
    title: "Heart of Darkness",
    genre: "Classics",
    date: "01-10-2003",
  },
  {
    author: "Rick Riordan (Goodreads Author)",
    title: "The Battle of the Labyrinth",
    genre: "Fantasy",
    date: "06-03-2008",
  },
  {
    author: "William Shakespeare",
    title: "A Midsummer Night's Dream",
    genre: "Classics",
    date: "28-07-2016",
  },
  {
    author: "Cassandra Clare (Goodreads Author)",
    title: "Clockwork Princess",
    genre: "Fantasy",
    date: "05-09-2013",
  },
  {
    author: "Kahlil Gibran",
    title: "The Prophet",
    genre: "Poetry",
    date: "01-01-2010",
  },
  {
    author: "Marion Zimmer Bradley",
    title: "The Mists of Avalon",
    genre: "Fantasy",
    date: "15-07-2001",
  },
  {
    author: "Rick Riordan (Goodreads Author)",
    title: "The Titan's Curse",
    genre: "Fantasy",
    date: "05-05-2007",
  },
  {
    author: "Rick Riordan (Goodreads Author)",
    title: "The Sea of Monsters",
    genre: "Fantasy",
    date: "01-04-2006",
  },
  {
    author: "Amy Tan (Goodreads Author)",
    title: "The Joy Luck Club",
    genre: "Fiction",
    date: "21-09-2006",
  },
  {
    author: "Jane Carruth (Adapted By)",
    title: "Alice in Wonderland",
    genre: "Classics",
    date: "07-09-2004",
  },
  {
    author: "Jack London",
    title: "The Call of the Wild",
    genre: "Classics",
    date: "01-01-2001",
  },
  {
    author: "Richard Bach (Goodreads Author)",
    title: "Jonathan Livingston Seagull",
    genre: "Fiction",
    date: "07-02-2006",
  },
  {
    author: "Gustave Flaubert",
    title: "Madame Bovary",
    genre: "Classics",
    date: "28-10-2004",
  },
  {
    author: "Norton Juster",
    title: "The Phantom Tollbooth",
    genre: "Fantasy",
    date: "28-10-1996",
  },
  {
    author: "Katherine Paterson",
    title: "Bridge to Terabithia",
    genre: "Young Adult",
    date: "06-10-2009",
  },
  {
    author: "Suzanne Collins",
    title: "The Hunger Games Trilogy Boxset",
    genre: "Young Adult",
    date: "24-08-2010",
  },
  {
    author: "Dr. Seuss",
    title: "Oh, the Places You'll Go!",
    genre: "Childrens",
    date: "22-01-1990",
  },
  {
    author: "Stieg Larsson",
    title: "The Girl Who Played with Fire",
    genre: "Fiction",
    date: "28-07-2009",
  },
  {
    author: "James Dashner (Goodreads Author)",
    title: "The Maze Runner",
    genre: "Young Adult",
    date: "06-10-2009",
  },
  {
    author: "Michael Ende",
    title: "The Neverending Story",
    genre: "Fantasy",
    date: "28-10-1997",
  },
  {
    author: "Charles Dickens",
    title: "Oliver Twist",
    genre: "Classics",
    date: "28-10-2003",
  },
  {
    author: "James Joyce",
    title: "Ulysses",
    genre: "Classics",
    date: "28-10-1990",
  },
  {
    author: "Robert Louis Stevenson",
    title: "Treasure Island",
    genre: "Classics",
    date: "15-09-2001",
  },
  {
    author: "E.L. James (Goodreads Author)",
    title: "Fifty Shades of Grey",
    genre: "Romance",
    date: "25-05-2011",
  },
  {
    author: "Jean M. Auel",
    title: "The Clan of the Cave Bear",
    genre: "Historical Fiction",
    date: "06-10-2016",
  },
  {
    author: "George R.R. Martin",
    title: "A Storm of Swords",
    genre: "Fantasy",
    date: "04-03-2003",
  },
  {
    author: "Geoffrey Chaucer",
    title: "The Canterbury Tales",
    genre: "Classics",
    date: "30-01-2003",
  },
  {
    author: "John Irving (Goodreads Author)",
    title: "The World According to Garp",
    genre: "Fiction",
    date: "01-04-1999",
  },
  {
    author: "Ernest Hemingway",
    title: "A Farewell to Arms",
    genre: "Classics",
    date: "28-10-2004",
  },
  {
    author: "Charles Dickens",
    title: "David Copperfield",
    genre: "Classics",
    date: "28-10-2004",
  },
  {
    author: "Jay Asher (Goodreads Author)",
    title: "Tote M\u00e4dchen l\u00fcgen nicht",
    genre: "Young Adult",
    date: "16-03-2009",
  },
];

export { records };
